### ISSUE TITLE
yolov5_tflite_video_inference.py for webcam (CPU and RPI4)

### ISSUE THREAD

**Issue by nocolour** [karanjakhar/yolov5-export-to-cpu#1]
yolov5_tflite_video_inference.py 

parser.add_argument('-v','--video_path', type=str, required=True, help='video path')  # file/folder, 0 for webcam

how to make it work with camera (either webcam or Picamera)

like this? tested with mp4 video file no problem, but webcam not work.
python yolov5_tflite_video_inference.py --weights yolov5s-fp16.tflite --video_path 0

**Comment by karanjakhar** [comment]
Please wait. I will upload an example for the webcam also.

**Comment by karanjakhar** [comment]
I have added a webcam script also. Please try that. 
`python3 yolov5_tflite_webcam_inference.py -w yolov5s-fp16.tflite`

**Comment by nocolour** [comment]
> 
> 
> I have added a webcam script also. Please try that.
> `python3 yolov5_tflite_webcam_inference.py -w yolov5s-fp16.tflite`

Great. Thank you very much

**Comment by nocolour** [comment]
> python3 yolov5_tflite_webcam_inference.py -w yolov5s-fp16.tflite

Background recording is working with webcam, but didn't show on desktop screen. 
Can you make it display on desktop screen for realtime view. tq

**Comment by karanjakhar** [comment]
Done. Please try now.

**Comment by nocolour** [comment]
> 
> 
> Done. Please try now.

working, but slow...
Thank you. Good Job
