### ISSUE TITLE
Need optimise the performance

### ISSUE THREAD

**Issue by nocolour** [karanjakhar/yolov5-export-to-cpu#2]
Hi,

I think the main purpose of using tflite (tensorflow lite) is for PC not support CUDA or don't have high end GPU.
I tested with tflite mobilenet v1 can get 3~6 FPS. With yolov5-tflite only can get 0.4 ~ 0.9 FPS with --img 416, it is too slow.
I convert it to --img 160 than only can get 3~4 FPS, still slow. If can get it around 6FPS will be better. 

Anyway to increase the performance?
--img 416
![yolov5Lite-416](https://user-images.githubusercontent.com/6244952/125021155-ac05f380-e0ac-11eb-809f-a7f2f0a742a5.png)

--img 160
![yolov5Lite-160](https://user-images.githubusercontent.com/6244952/125021190-ba540f80-e0ac-11eb-83a4-490d634b4a94.png)

**Comment by karanjakhar** [comment]
You are using the raspberry pi code on the desktop. Please try the CPU version. As raspberry pi one is using tflite_runtime and desktop CPU one is using TensorFlow. 
I am getting around 3 FPS with 416: 
![Screenshot from 2021-07-09 12-33-38](https://user-images.githubusercontent.com/29913676/125037795-3a30a880-e0b2-11eb-86bb-6a91386d1eca.png)

**Comment by nocolour** [comment]
> 
> 
> You are using the raspberry pi code on the desktop. Please try the CPU version. As raspberry pi one is using tflite_runtime and desktop CPU one is using TensorFlow.
> I am getting around 3 FPS with 416:
> ![Screenshot from 2021-07-09 12-33-38](https://user-images.githubusercontent.com/29913676/125037795-3a30a880-e0b2-11eb-86bb-6a91386d1eca.png)

I tested with linux, it's faster than Windows 10. The performance different in linux and windows.
Anyway I convert the tflite to 256 rather than 416, I able to get 7 FPS for CPU. 256 for Raspbery Pi4 can get 4 FPS, detection also working well.
Thank you
