### ISSUE TITLE
defualt argument for --weights

### ISSUE THREAD

**Issue by nocolour** [karanjakhar/yolov5-export-to-cpu#3]
parser.add_argument('-w','--weights', type=str, **default='yolov5s.pt'**, **help='model.pt path(s)**')

I suggest change it to 
" parser.add_argument('-w','--weights', type=str, **default=yolov5s-fp16.tflite'**, **help='model.tflite path(s)**') "

python3 yolov5_tflite_webcam_inference.py -w yolov5s-fp16.tflite  ==> python3 yolov5_tflite_webcam_inference.py

**Comment by karanjakhar** [comment]
Thank you for the suggestion. Done.
Please do let me know if you have any other suggestions.
